- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: learningdevopsaws.online
    instances:
    - db
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-everything #replace with you AWS values
      image_id: ami-041e2ea9402c46c32
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instances_info

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{ ec2_instances_info }}"

  - name: create r53 records
    amazon.aws.route53:
      command: create
      zone: learningdevopsaws.online
      record: " {{ instances }}.{{ zone }}"
      type: A
      value: "{{ item.instances.private_ip_address }}"
      overwrite: true
      ttl: 1
      wait: true
    loop: "{{ ec2_instances_info.results }}"
    